### ISSUE TITLE
127.0.0.1 refused to connect

### ISSUE THREAD

**Issue by shijiewei** [javascript-tutorial/server#105]
I'v already done following the [Tutorial Server](https://github.com/javascript-tutorial/server?tab=readme-ov-file#installation). And successfully accessed the docs through 'http://127.0.0.1:3000' for days.

But today I restarted my MacBook and repeat the following steps:
1) cd xxx/js/server
2) ./edit en
  got cmd output: '03:58:22.542Z  INFO importWatch: Import complete'
3) access 'http://127.0.0.1:3000' in browser
but I just got the following error(both in Chrome and Safari):

> This site can’t be reached.
>127.0.0.1 refused to connect.
>ERR_CONNECTION_REFUSED

What's wrong with my operation?

OS: MacOS Sonoma 14.3
Node.js version: v18.14.1

**Comment by smith558** [comment]
This is a client-side issue. Try first https://kinsta.com/blog/err_connection_refused/.

**Comment by tarasyyyk** [comment]
Using `http://localhost:3000/` worked for me.

**Comment by smith558** [comment]
@shijiewei Can you confirm if you're still having any issues?
