### ISSUE TITLE
导入中文（zh）的版本卡了很久

### ISSUE THREAD

**Issue by ivanlee93** [javascript-tutorial/server#24]
![image](https://user-images.githubusercontent.com/22174857/54811913-c857a980-4cc4-11e9-9fff-2d94d333bde9.png)

**Comment by iliakan** [comment]
It hangs?

**Comment by iliakan** [comment]
Did you wait a few minutes?

**Comment by ivanlee93** [comment]
There are about 10 minutes, resource address is: https://github.com/xitu/javascript-tutorial-zh
English is not good

**Comment by iliakan** [comment]
Slow computer?
