### ISSUE TITLE
The header overlaps the div.content

### ISSUE THREAD

**Issue by dimabubenok** [javascript-tutorial/server#30]
Now in all articles the header overlaps the div.content because margin-bottom -30px
server/modules/styles/blocks/main/main.styl 
```
&__header
      margin 20px 0 -30px 0
```

**Comment by iliakan** [comment]
Clear browser cache? Which browser?

**Comment by dimabubenok** [comment]
Chrome v73, cache cleared.

**Comment by dimabubenok** [comment]
![Снимок экрана 2019-04-16 в 15 39 41](https://user-images.githubusercontent.com/2875575/56194828-f333e400-605d-11e9-9073-1eaa071406e4.png)

**Comment by iliakan** [comment]
Fixed.

**Comment by iliakan** [comment]
Thanks!
