### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by ibragimof** [javascript-tutorial/server#33]
I followed instruction in README.
When I'm trying to start server with code
`
w4@MSI MINGW64 /e/js/server (master)
$ ./edit en
`
I got this error (as well as for "./edit ru ru"):
`
'NODE_PRESERVE_SYMLINKS' is not recognized as an internal or external command,   operable program or batch file.
`

**Comment by iliakan** [comment]
Why are you using mingw64, not native windows?

**Comment by ibragimof** [comment]
Because **mingw64** is git default bash for windows and it much more prettier than CMD native console.
Whatever it was, your way works. Thanks.

**Comment by iliakan** [comment]
It should work in mingw too.
