### ISSUE TITLE
Server not running

### ISSUE THREAD

**Issue by RenGanitano** [javascript-tutorial/server#34]
OS: Windows 10
Node: 10.16.0

CMD seems to hang at import complete and nothing is showing up on localhost

**Comment by iliakan** [comment]
Please pull latest changes and reinstall modules.

**Comment by RenGanitano** [comment]
Works like a charm, appreciate the quick help! What was the issue if you don't mind me asking?

**Comment by iliakan** [comment]
A slight modules update regression =)
