### ISSUE TITLE
Github link not working in sidebar

### ISSUE THREAD

**Issue by afreen23** [javascript-tutorial/server#36]
On clicking the link to `Edit on Github` in the bottom-left of sidebar, the 404 not found github page appears for [this](https://javascript.info/symbol) and most of the pages.
![issue](https://user-images.githubusercontent.com/25664409/59230328-bf5ae200-8bfa-11e9-837f-f6e711a1f6e8.png)

**Comment by iliakan** [comment]
Thanks a lot for reporting! Fixed.
