### ISSUE TITLE
Texts are blurry in the codebox when I dragged

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/server#37]
symptom:
![image](https://user-images.githubusercontent.com/6451384/59659690-af866380-91e1-11e9-9dff-cdce9952ce75.png)

reason of the blurred text(shadow):
![image](https://user-images.githubusercontent.com/6451384/59659742-cb8a0500-91e1-11e9-8845-22bb1277c460.png)

after modifying css:
![image](https://user-images.githubusercontent.com/6451384/59659981-5f5bd100-91e2-11e9-9fa4-c2d00f84ea09.png)
![image](https://user-images.githubusercontent.com/6451384/59659914-3dfae500-91e2-11e9-9d6f-fba6b358f5b8.png)
![image](https://user-images.githubusercontent.com/6451384/59659764-d8a6f400-91e1-11e9-95ae-ab2592086d77.png)

**Comment by iliakan** [comment]
Which browser/OS is that? How to reproduce? Just select and drag?

**Comment by Violet-Bora-Lee** [comment]
Win10/chrome. Yea you could reproduce when you drag the texts in the codebox

**Comment by iliakan** [comment]
Right, sorry for the delay.
Not sure why this shadow was even needed.
