### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by lomeat** [javascript-tutorial/server#43]
Maybe I just did not find it, but in theory, the button for switching the theme should be in an obvious easily found place. It would be cool to see a dark version, because at night, a dark editor is perceived nicely, and a bright website mercilessly blinds. No matter what the brightness, in any case, a strong contrast.

I would have done it myself, but I could not figure out how the server works. If I succeed, it will be a good experience.

**Comment by TheUniParse** [comment]
me too, I use dark mode both at day/night
hi @lomeat, did you find solution so far?

**Comment by iliakan** [comment]
Dark theme is enabled on production.
