### ISSUE TITLE
invalid command

### ISSUE THREAD

**Issue by tarasyyyk** [javascript-tutorial/server#44]
On macOS the follow command from Readme isn't working:
`NODE_LANG=zh glp engine:koa:tutorial:figuresTranslate --image try-catch-flow.svg`

This one is working but for all images, even if I set `--image`:
`NODE_LANG=ru npm run gulp engine:koa:tutorial:figuresTranslate --image variable.svg`

I tried `--image variable.svg`, `--image=variable.svg`, `--image="varibale.svg"`, but all of them generates all translation for images (I need for specific one).

~~The second issue I found is word `"Hello!"` in `1-js/02-first-steps/04-variables/variable.svg`. How to translate this text?~~
images.yml
```
variable.svg:
  "Hello!": '"Привет!"'  // should be: '"Hello!"': '"Привіт!"'
  message: 'Сообщение'
```

Can I simply edit svg images directly without changing `images.yml` ?
This variant is better for me, because I can exactly change position of text (by changing `x` and `y` attributes) and even font-size.

**Comment by iliakan** [comment]
1. Please git pull latest code for server and engine.
2. Please use `NODE_LANG=uk`

**Comment by iliakan** [comment]
Does it work now?

**Comment by tarasyyyk** [comment]
I cloned these repos 1 hour ago.
Sorry, I didn't see any new changes. My repos are up to date.
The latest commit is https://github.com/javascript-tutorial/server/commit/adc515631aa6cca7ddbe4d49f5a17bc930e0e7ea

**Comment by iliakan** [comment]
Let me know if problems still exist =)
