### ISSUE TITLE
 binaries can't be found error

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/server#45]
After the pngs are changed svgs, I've got such error.

![image](https://user-images.githubusercontent.com/6451384/62244487-7ebd5f00-b41a-11e9-94f0-6020a0524b6c.png)

The reason for the error is that the server searches the image files in en directory not ko directory(in my case). You can see the error message on the image.

**Comment by iliakan** [comment]
How can I reproduce that?

**Comment by Violet-Bora-Lee** [comment]
You could reproduce the issue deleting en directory in your local machine and only set foreign project such as ko, I guess.

**Comment by Violet-Bora-Lee** [comment]
I may need to add this issue on the engine repository. It's time to look around server-side codes for me.

**Comment by iliakan** [comment]
I can do that. Delete English and run `./edit ko`?

**Comment by Violet-Bora-Lee** [comment]
Yes :)

**Comment by iliakan** [comment]
And then...? Should I re-translate  an image or  edit an article?

**Comment by Violet-Bora-Lee** [comment]
No. You could reproduce the issue when you delete en directory and have another directory but en on localmachine. Couldn't you reproduce the issue?

**Comment by iliakan** [comment]
I deleted English folder.
Then run `./edit ru` (shouldn't matter).

Then everything was ok.

Maybe I need to  do something else.

**Comment by Violet-Bora-Lee** [comment]
Oh, I see. I'll try other languages but Korean.

**Comment by iliakan** [comment]
I will try korean.

**Comment by iliakan** [comment]
![image](https://user-images.githubusercontent.com/349336/62360034-a0087300-b520-11e9-883b-0c009d432904.png)

**Comment by iliakan** [comment]
Most likely, you don't have imagemagick installed. =)

**Comment by iliakan** [comment]
Need help with that?

**Comment by Violet-Bora-Lee** [comment]
I'm using Windows 10 and Chocolatey, package manager for Windows. I've installed `graphicsmagick` and `imagemagick` using Chocolatey but had the same issue. I've also tried to install both packages by installing binary files. Phew :( :(

I'll try more to resolve the issue on my local machine. Anyway, I can see that it's not the problem comes from your code but mine.

Thanks for your trying 👍

**Comment by Violet-Bora-Lee** [comment]
[for Windows 10 user]

GraphicsMagick Download Link: ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/windows/
ImageMagick Download Link: http://www.imagemagick.org/script/download.php#windows


The cause of the issue comes from ImageMagick.

![image](https://user-images.githubusercontent.com/6451384/62426781-791a8e80-b724-11e9-8275-e9fe8751fee6.png)


When you install ImageMagick, there are some default checked boxes like the image above. When you haven't touched anything and keep installing, the same issue will occur.

![image](https://user-images.githubusercontent.com/6451384/62426806-c434a180-b724-11e9-900c-2392c06c1682.png)

So, I've set like this and the issue no longer has occurred.
