### ISSUE TITLE
What is the proper way to load an extra CSS file?

### ISSUE THREAD

**Issue by Goudarz** [javascript-tutorial/server#47]
I am working on translation to Persian, which is Right-to-left language. For that, I need to customize the CSS to load the pages in the proper format.

**Comment by iliakan** [comment]
Let me add it for you, as an example. What is needed and where?

**Comment by Goudarz** [comment]
I want to put the `rtl.css` file in the `head` tag.

**Comment by iliakan** [comment]
1) Will your `rtl.css` also work for Arabic? Or it's Persian only?
2) Can it be in Stylus (preprocessor) format? `rtl.styl`

**Comment by Goudarz** [comment]
1. Works for all [RTL Direction](https://www.w3.org/International/questions/qa-scripts.en#examples) languages: Persian, Arabic, Hebrew , etc.
2. Yes, I can.

**Comment by iliakan** [comment]
I added `rtl.styl` for `fa` language.

But it requires the server language to exist. 
You need `fa.yml` at the same places where `en.yml` exists, and then `./edit fa fa` to run the server in Persian.
