### ISSUE TITLE
Edit server doesn't run

### ISSUE THREAD

**Issue by ibragimof** [javascript-tutorial/server#52]
I use this feature (edit) for offline learning JS. So after installation a new node and gulp I got this error:
`'edit' errored after 946 ms
The following tasks did not complete: webpack, livereload, server
Did you forget to signal async completion?`

There is any problem with my gulp version?
![2020-3-17 18-4-26](https://user-images.githubusercontent.com/47029060/77233517-ca02c880-6bc9-11ea-8416-a7fad9353e6b.png)

**Comment by iliakan** [comment]
Must be gulp 4

**Comment by ibragimof** [comment]
> Must be gulp 4

`CLI version: 2.2.0
Local version: 4.0.2`

**Comment by iliakan** [comment]
So that's not a gulp problem. Maybe you don't have the tutorial text checked out or another problem.
