### ISSUE TITLE
Trouble Booting Up Server For Persian (Farsi) Lang

### ISSUE THREAD

**Issue by mehradsadeghi** [javascript-tutorial/server#63]
Hi.
There seems to be a problem when trying to import Persian language into server.
| Node  | 10.21.0  |
|-|-|
| NPM  | 6.14.4   |
| OS  | Ubuntu 18.04   |

![image](https://user-images.githubusercontent.com/31504728/87880955-1ab8ef80-ca0b-11ea-846b-c711bee71f90.png)

Any solution would be appreciated.

**Comment by AMIRABEDINI** [comment]
Hi everyone
I have the same problem, but with a different approach

- windows10 2004
- npm@6.14.5
- node 12.18.2

![1](https://user-images.githubusercontent.com/48311889/87883892-cbc98500-ca1f-11ea-97d6-0071b845d30b.PNG)
![2](https://user-images.githubusercontent.com/48311889/87883894-cff5a280-ca1f-11ea-8f52-2992f24400ad.PNG)
![3](https://user-images.githubusercontent.com/48311889/87883895-d257fc80-ca1f-11ea-863a-dfba768f6a76.PNG)

**Comment by iliakan** [comment]
There's a duplicate article with the same name "..-prototype-inheritance".

You'll need to correct that, see the English version for the original please.
