### ISSUE TITLE
postcss-loader v4.0.0 released

### ISSUE THREAD

**Issue by hysimok** [javascript-tutorial/server#68]
Due to the latest version of postcss-loader(v4.0.0) released on 9/7, an error `ModuleBuildError` occurs.

👇 Error message:
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
```
Check major changes in [release note](https://github.com/webpack-contrib/postcss-loader/releases/tag/v4.0.0), 
* PostCSS (plugins/syntax/parser/stringifier) options was moved to the postcssOptions option, please look at docs

There are two ways to fix this.
1. Change `PostCss` to `postcssOptions`
2. Fix postcss-loader version to 3.0.0 in `package.json`

The first method seems better, so let me make a pull request using the first method.

**Comment by iliakan** [comment]
Thanks, we'll be staying on 3 for some time.
