### ISSUE TITLE
[Bug report] - local server error due to "js-yaml" update

### ISSUE THREAD

**Issue by C17AN** [javascript-tutorial/server#75]
Hello! I found there's a problem with running tutorial server.
By following [this](https://github.com/javascript-tutorial/server) server guide, I should encounter this error, "Function yaml.safeLoad is removed in js-yaml 4."...

### Printing Error with current guide

![image](https://user-images.githubusercontent.com/26535030/107630044-574d8080-6ca6-11eb-9c25-402c14865356.png)

I think server code should be modified, or using the old version of "js-yaml".

### After replacing "js-yaml" to old version(3.14.1)

![image](https://user-images.githubusercontent.com/26535030/107630252-9c71b280-6ca6-11eb-9784-55157f39bedc.png)

How about replacing "js-yaml": "*" to "js-yaml" : "3.14.1" in package.json?

**Comment by iliakan** [comment]
Updated.

**Comment by iliakan** [comment]
Thanks!
