### ISSUE TITLE
Instruction regarding Language-Specific-Repo is not right

### ISSUE THREAD

**Issue by Showrin** [javascript-tutorial/server#77]
In the installation section, at point no 5, it's been said to clone the language repo (for example, bn.javascript.info) in `js/server/repo/` directory.
I did so. But when I ran `./edit  bn`, it was throwing an error that was:
```
Error: ENOENT: no such file or directory, lstat 'F:\............\js\bn.javascript.info'
```
Then I cloned the repo again in the js folder. And then my server started running without any problem.
So this is the problem I faced. I think instruction in the readme section should be changed.

**Comment by iliakan** [comment]
Please git pull the latest code.

**Comment by iliakan** [comment]
Thanks for the report!
