### ISSUE TITLE
[Bug report] local server page next button css styling broken

### ISSUE THREAD

**Issue by wSeungMi** [javascript-tutorial/server#89]
Hello! 
I found the layout problem on the local server.

### Issue
![image](https://user-images.githubusercontent.com/104605709/192525623-355500f0-eff3-4d3b-8241-82d84841d25f.png)

The page layout broken when the Local Server is running, so can’t use the next button.

The location of the file is <code>server/modules/styles/blocks/page/page.styl</code>
### Fix
```css
/* edit before */
&__nav_next
    left 0
    transition top animation_duration
```

```css
/* edit after */
&__nav_next
    right 0
    transition top animation_duration
```
I think I need to fix it like.

so I registered the issue and upload the PR, so please check it.
Thank you :)

**Comment by iliakan** [comment]
Fixed, I hope =)
