### ISSUE TITLE
`edit.cmd fa` fails: node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by alivarastepour** [javascript-tutorial/server#93]
So I followed the instructions in `readme.md`, the following command
```
edit.cmd fa
```
leads to the following:
```
D:\js\server>call gulp edit   | bunyan
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

D:\js\server>goto :eof
```

I tried solving it:
```
set NODE_OPTIONS=
```
but the value of `NODE_OPTIONS` resets everytime.
any ideas?

**Comment by skafridi07** [comment]
just comment out or remove the NODE_OPTIONS line in edit file and rerun it.

**Comment by alivarastepour** [comment]
> just comment out or remove the NODE_OPTIONS line in edit file and rerun it.

did not work

**Comment by Peter-developer01** [comment]
> just comment out or remove the NODE_OPTIONS line in edit file and rerun it.

did work for me

**Comment by iliakan** [comment]
Fixed.
